apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: mchama
spec:
  replicas: 5
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: 172.104.253.95:8095/mobigrow/com.wati.config.server:latest
          ports:
            - containerPort: 8101
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: config-server-config