apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: 172.104.253.95:8095/mobigrow/com.wati.config.server:latest
          ports:
            - containerPort: 8101
          volumeMounts:
            - name: config-server-data
              mountPath: /var/lib/config-server
      volumes:
        - name: config-server-data
          persistentVolumeClaim:
            claimName: config-server-data-pvc
