---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: mchama
spec:
  selector:
    app: config-server
  ports:
    - name: http
      port: 8888
      targetPort: 8101
  type: LoadBalancer
